{% set name = 'bob.pipelines' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  ruin_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt
    # installs the documentation source, readme to share/doc so it is available
    # during test time
    - install -d "${PREFIX}/share/doc/{{ name }}"
    - cp -R README.rst requirements.txt doc "${PREFIX}/share/doc/{{ name }}/"

requirements:
  host:
    - python
    - setuptools
    # bob dependencies
    - bob.extension
    - bob.io.base
    - bob.db.base
    # other libraries
    - numpy {{ numpy }}
    - dask {{ dask }}
    - dask-jobqueue {{ dask_jobqueue }}
    - distributed {{ distributed }}
    - scikit-learn {{ scikit_learn }}
    - xarray {{ xarray }}
    - h5py {{h5py}}
    # test requirements
    - dask-ml {{ dask_ml }}
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('dask') }}
    - {{ pin_compatible('dask-jobqueue') }}
    - {{ pin_compatible('distributed') }}
    - {{ pin_compatible('scikit-learn') }}
    - {{ pin_compatible('xarray') }}
    - {{ pin_compatible('h5py') }}
  run_constrained:
    - {{ pin_compatible('dask-ml') }}

test:
  imports:
    - {{ name }}
  commands:
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme
    - dask-ml

about:
  summary: Tools to build robust and extensible pipelines
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-Clause
  license_family: BSD
  license_file: ../LICENSE
